#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

terms = [1,2]
sum = 0


while terms[0] < 4000000 and terms[1] < 4000000:
	for counter in range(2):
		if terms[0] % 2 == 0:
			sum += terms[0]
		nextTerm = terms[1] + terms[0]
		terms[0] = terms[1]
		terms[1] = nextTerm

print(sum)
